config/routes.rb
Rails.application.routes.draw do
  
  namespace :public do
    get 'communities/index'
    get 'communities/new'
    get 'communities/show'
    get 'communities/edit'
  end
  devise_for :owners, controllers: {
    sessions:      'owners/sessions',
    passwords:     'owners/passwords',
    registrations: 'owners/registrations',
    confirmations: 'owners/confirmations',
    omniauth: 'owners/omniauth',
    unlocks: 'owners/unlocks'
  }
  
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
  }
  
  devise_scope :admin do
    get 'admin', to: 'admins/sessions#new'
  end
  

  namespace :admin do
    resources :hospitals, only: [:index, :destroy]
    
    resources :chinchillas, only: [:index, :destroy]
    
    resources :posts, only: [:index, :destroy, :show] do
      resources :post_comments, only: [:destroy]
    end
    
    resources :owners, only: [:index, :destroy]
    
    resources :questions, only: [:index, :destroy, :show] do
      resources :question_comments, only: [:destroy]
    end
    
  end

    
  
  scope module: :public do
    resources :owners, only: [:show, :edit, :update]
    get 'confirmation/:id' => 'owners#withdrawal_confirmation', as: 'confirm_unsubscribe'
    patch 'withdraw/:id' => 'owners#withdrawal', as: 'withdraw_owner'
    put 'withdraw/:id' => 'ownerss#withdraw'    
    
    resources :chinchillas do
      resource :favorite_chinchillas, only: [:index, :create, :destroy]
    end
    
    resources :posts do
      resource :favorite_posts, only: [:index, :create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    
    resources :hospitals
    
    resources :questions do
      resources :question_comments, only: [:create, :destroy]
    end
    patch 'solved' => 'questions#solved'
    
    get   'contact' => 'contacts#new' 
    post  'contact/confirm' => 'contacts#confirm' 
    post  'contact/thanks'  => 'contacts#thanks'
  end


  
  root to: 'homes#top'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
        # :registerable,
        # :recoverable, 
        # :rememberable, 
         :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chinchilla.rb
class Chinchilla < ApplicationRecord
  belongs_to :owner
  has_many :posts, dependent: :destroy
  has_many :favorite_chinchillas, dependent: :destroy
  
  validates :name, presence: true
  validates :birthday, presence: true
  validates :sex, presence: true
  validates :fur_type, presence: true
  validates :introduction, length: { maximum: 140 }
  
  
  attachment :image
  enum sex: { "オス": 0, "メス": 1 }
  
  def favorited_by?(owner)
    favorite_chinchillas.where(owner_id: owner.id).exists?
  end
  
  
end

app/models/community.rb
class Community < ApplicationRecord
end

app/models/community_member.rb
class CommunityMember < ApplicationRecord
  belongs_to :community_members
  belongs_to :owner
end

app/models/community_message.rb
class CommunityMessage < ApplicationRecord
  belongs_to :community
  belongs_to :owner
end

app/models/favorite_chinchilla.rb
class FavoriteChinchilla < ApplicationRecord
  belongs_to :owner
  belongs_to :chinchilla
end

app/models/favorite_post.rb
class FavoritePost < ApplicationRecord
  belongs_to :owner
  belongs_to :post
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  belongs_to :owner
  has_many :hospital_images, dependent: :destroy
  
  accepts_attachments_for :hospital_images, attachment: :image
  
  validates :hospital_name, presence: true
  
  validates :address, presence: true
  
  validates :rate, numericality: { less_than_or_equal_to: 5,
                                   greater_than_or_equal_to: 0 }, 
                   presence: true
  
  validates :comment, presence: true
                      
  
  geocoded_by :address
  after_validation :geocode
end

app/models/hospital_image.rb
class HospitalImage < ApplicationRecord
  belongs_to :hospital
  attachment :image
  
  
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :chinchillas, dependent: :destroy
  has_many :hospitals, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :question_comments, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorite_posts, dependent: :destroy
  has_many :favorite_chinchillas, dependent: :destroy
  has_many :community_members
  has_many :communities, through: :community_members
  has_many :community_messages, dependent: :destroy
  attachment :image
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: true
                       
  validates :name, presence: true
  
  validates :prefecture, presence: true
  
  validates :introduction, length: { maximum: 140 }
                       
  
 enum prefecture:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
   }
   
  # 退会後のログインを拒否
  def active_for_authentication?
    super && (self.join_status == true)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :chinchilla
  has_many :post_comments, dependent: :destroy
  has_many :favorite_posts, dependent: :destroy
  attachment :image
  
  validates :post_title, presence: true,
                         length: { maximum: 20 }
  
  validates :post_body, length: { in: 2..140 }
  
                       
  
  def favorited_by?(owner)
    favorite_posts.where(owner_id: owner.id).exists?
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :owner
  belongs_to :post
  
  validates :comment, presence: true,
                      length: { in: 2..140 }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :owner
  has_many :question_images, dependent: :destroy
  has_many :question_comments, dependent: :destroy
  accepts_attachments_for :question_images, attachment: :image
  
  validates :question_title, presence: true,
                             length: { in: 2..30 }
                             
  validates :question_body, presence: true
  
  validates :solution_status, inclusion: { in: [true, false] }
                          
end

app/models/question_comment.rb
class QuestionComment < ApplicationRecord
  belongs_to :owner
  belongs_to :question
  
  validates :comment, presence: true
end

app/models/question_image.rb
class QuestionImage < ApplicationRecord
  belongs_to :question
  attachment :image
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
    
    def after_sign_in_path_for(resource)
      case resource
      when Owner
        owner_path(resource)
      when Admin
        admin_owners_path
      end
    end
  
    def after_sign_out_path_for(resource)
      root_path
    end
  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :prefecture])
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @owner = Owner.new
    @randoms = Post.order("RAND()").limit(6)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :owner
  end

  def resource
    @resource ||= Owner.new
  end

  def resource_class
    Owner
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:owner]
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_admin_navbar.html.erb
  <div class="d-none d-lg-block">
    <div class="logo mt-3 mb-3">
      <%= link_to admin_owners_path do %>
        <%= image_tag asset_path("pf-images/logo.png"), size: "150x60" %>
      <% end %>
    </div>
    <div>
      <%= link_to " 飼い主", admin_owners_path, class: "fas fa-user mt-3 mb-3" %>
    </div>
    <div>
      <%= link_to " チンチラ", admin_chinchillas_path, class: "fas fa-paw mt-3 mb-3" %>
    </div>
    <div>
      <%= link_to " 投稿", admin_posts_path, class: "fas fa-carrot mt-3 mb-3" %>
    </div>
    <div>
      <%= link_to " 病院レビュー", admin_hospitals_path, class: "fas fa-hospital-alt mt-3 mb-3" %>
    </div>
    <div>
      <%= link_to " 相談", admin_questions_path, class: "fas fa-question mt-3 mb-3" %>
    </div>
     <div>
      <%= link_to " ログアウト", destroy_admin_session_path, method: :delete, class: "fas fa-sign-out-alt mt-3 mb-3" %>
    </div>  
  </div>

  <div class="d-block d-lg-none">
    <div class="logo mt-3 mb-3">
      <%= link_to admin_owners_path do %>
        <%= image_tag asset_path("pf-images/logo.png"), size: "50x20" %>
      <% end %>
    </div>
    <div>
      <%= link_to "", admin_owners_path, class: "fas fa-user mt-3 mb-3" %>
    </div>
    <div>
      <%= link_to "", admin_chinchillas_path, class: "fas fa-paw mt-3 mb-3" %>
    </div>
    <div>
      <%= link_to "", admin_posts_path, class: "fas fa-carrot mt-3 mb-3" %>
    </div>
    <div>
      <%= link_to "", admin_hospitals_path, class: "fas fa-hospital-alt mt-3 mb-3" %>
    </div>
    <div>
      <%= link_to "", admin_questions_path, class: "fas fa-question mt-3 mb-3" %>
    </div>
     <div>
      <%= link_to "", destroy_admin_session_path, method: :delete, class: "fas fa-sign-out-alt mt-3 mb-3" %>
    </div>     
  </div>
    
 

app/views/layouts/_error.html.erb
<% if object.errors.any? %>
<div class="error-messages">
  <h3><%= pluralize(object.errors.count, "error") %> prohibited this obj from being saved:</h3>
  <ul>
      <% object.errors.full_messages.each do |message| %>
        <li>
            <%= message %>
        </li>
      <% end %>
  </ul>
  
</div>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="error-messages">
    <h3><%= object.errors.count %> 件のエラーが発生しました</h3>
    <ul>
        <% object.errors.full_messages.each do |message| %>
          <li>
              <%= message %>
          </li>
        <% end %>
    </ul>
    
  </div>
<% end %>

app/views/layouts/_leftbar.html.erb
<div class="d-none d-lg-block">
  
  <div class="logo mt-3 mb-3">
    <%= link_to owner_path(current_owner) do %>
      <%= image_tag asset_path("pf-images/logo.png"), size: "150x60" %>
    <% end %>
  </div>
  <div>
    <%= link_to " プロフィール", owner_path(current_owner), class: "fas fa-user mt-3 mb-3" %>
  </div>
  <div>
    <%= link_to " チンチラさん", chinchillas_path, class: "fas fa-paw mt-3 mb-3" %>
  </div>
  <div>
    <%= link_to " 投稿", posts_path, class: "fas fa-carrot mt-3 mb-3" %>
  </div>
  <div>
    <%= link_to " 病院レビュー", hospitals_path, class: "fas fa-hospital-alt mt-3 mb-3" %>
  </div>
  <div>
    <%= link_to " お悩み相談", questions_path, class: "fas fa-question mt-3 mb-3" %>
  </div>
   <div>
    <%= link_to " ログアウト", destroy_owner_session_path, method: :delete, class: "fas fa-sign-out-alt mt-3 mb-3" %>
  </div>    
</div>

<div class="d-block d-lg-none">
  <div class="logo mt-5 mb-3">
    <%= link_to owner_path(current_owner) do %>
      <%= image_tag asset_path("pf-images/logo.png"), size: "120x48" %>
    <% end %>
  </div>
  <div>
    <%= link_to "", owner_path(current_owner), class: "fas fa-user mt-3 mb-3", style: "font-size: 3rem;" %>
  </div>
  <div>
    <%= link_to "", chinchillas_path, class: "fas fa-paw mt-3 mb-3", style: "font-size: 3rem;" %>
  </div>
  <div>
    <%= link_to "", posts_path, class: "fas fa-carrot mt-3 mb-3", style: "font-size: 3rem;" %>
  </div>
  <div>
    <%= link_to "", hospitals_path, class: "fas fa-hospital-alt mt-3 mb-3", style: "font-size: 3rem;" %>
  </div>
  <div>
    <%= link_to "", questions_path, class: "fas fa-question mt-4 mb-3", style: "font-size: 3rem;" %>
  </div>
   <div>
    <%= link_to "", destroy_owner_session_path, method: :delete, class: "fas fa-sign-out-alt mt-4 mb-4", style: "font-size: 3rem;" %>
  </div>      
</div>

app/views/layouts/_navbar.html.erb
  <nav class="navbar sticky-top d-flex flex-column">
    <div class="logo mt-3 mb-3">
      <%= link_to posts_path do %>
        <%= image_tag "pf-images/logo.png", size: "175x70" %>
      <% end %>
    </div>
    <div>
      <%= link_to " ホーム", posts_path, class: "fas fa-home mt-3 mb-3" %>
    </div>
    <div>
      <%= link_to " チンチラさん", chinchillas_path, class: "fas fa-paw mt-3 mb-3" %>
    </div>
    <div>
      <%= link_to " 病院レビュー", hospitals_path, class: "fas fa-hospital-alt mt-3 mb-3" %>
    </div>
    <div>
      <%= link_to " プロフィール", owner_path(current_owner), class: "fas fa-user mt-3 mb-3" %>
    </div>
    <div>
      <a href="#" class="fas fa-users mt-3 mb-3" style="color: gray;"> コミュニティ</a>
    </div>
    <div>
      <a href="#" class="fas fa-envelope mt-3 mb-3" style="color: gray;"> メッセージ</a>
    </div>
     <div>
      <%= link_to " ログアウト", destroy_owner_session_path, method: :delete, class: "fas fa-sign-out-alt mt-3 mb-3" %>
    </div>
  
  </nav>

app/views/layouts/_notice.html.erb
<h6 id="notice"><%= flash[:notice] %></h6>

app/views/layouts/_rightbar.html.erb
<div class="random-post mt-1">
  <p>おすすめの投稿</p>
  <div class="d-flex flex-wrap justify-content-around">
    <% if @recommends %>
      <% @recommends.each do |recommend| %>
        <%= link_to post_path(recommend) do %>
          <%= attachment_image_tag recommend, :image, :fill, 80, 80, class: "random-image mt-1 mr-1" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="same-prefecture-owner mt-3">
  <p>同じ都道府県の主さん</p>
    <% if @same_prefecture_owners %>
      <% @same_prefecture_owners.each do |same_prefecture_owner| %>
        <%= link_to owner_path(same_prefecture_owner) do %>
          <div class="pb-2">
            <%= attachment_image_tag same_prefecture_owner, :image, :fill, 30, 30, fallback: asset_path("pf-images/profile_noimage.png"), size: "30x30", style: "border-radius: 50%;"%>
            <%= same_prefecture_owner.name %>さん
          </div>
        <% end %>
      <% end %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>おいでよ！チンチラの森</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= include_gon(init: true) %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <main>
      <% if owner_signed_in? %>
        <div class="container-fluid">
          <div class="row">
            <div class="left-bar col-2 text-center sticky-top">
              <%= render "layouts/leftbar" %>
            </div>
            <div class="center col-10 col-lg-7 mt-5">
              <%= render 'layouts/notice' %>
              <%= yield %>
            </div>
            <div class="right-bar d-none d-lg-block col-lg-3 sticky-top text-center">
              <%= render 'layouts/rightbar' %>
            </div>
          </div>
        </div>
      <% elsif admin_signed_in? %>
         <div class="container-fluid">
          <div class="row">
            <div class="left-bar col-2 text-center sticky-top">
              <%= render "layouts/admin_navbar" %>
            </div>
            <div class="center col-10 mt-5">
              <%= render partial: 'layouts/notice' %>
              <%= yield %>
            </div>
      <% else %>
        <%= yield %>
        <%= render partial: 'owners/registrations/new' %>
        <%= render partial: 'owners/sessions/new' %>
      <% end %>
    </main>

    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>
  </body>
</html>